version: "3.9"
services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: kanban-api
    ports:
      - "5121:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__Default=Data Source=/app/data/kanban.db
    volumes:
      - ./data:/app/data           # SQLite file 
    restart: unless-stopped

  web:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: kanban-web
    ports:
      - "5173:80"
    environment:
      # API base URL for Vite
      - VITE_API_BASE=http://localhost:5121
    depends_on:
      - api
