version: "3.9"
services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: kanban-api
    ports:
      - "5121:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080

  web:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: kanban-web
    ports:
      - "5173:80"
    environment:
      # Tarayıcı doğrudan host'taki API portuna gider.
      - VITE_API_BASE=http://localhost:5121
    depends_on:
      - api
